import React from 'react';
import { motion } from 'framer-motion';
import { CheckCircle, AlertTriangle, Info, MapPin, Code, ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';

const ReportCard = ({ data }) => {
  const [showRaw, setShowRaw] = useState(false);
  if (!data || !data.entry) return null;

  const bundle = data;
  const detectedLanguage = bundle.detectedLanguage;

  let observations = [];
  let clinicalFindings = "No findings";
  let clinicalScore = 0;
  let urgencyLevel = "UNKNOWN";
  let instructions = [];
  let referral = null;

  // Extract from strict FHIR R4 Bundle
  bundle.entry.forEach(item => {
    const res = item.resource;
    if (res.resourceType === 'Observation') {
      observations.push(res.valueString);
    } else if (res.resourceType === 'ClinicalImpression') {
      clinicalFindings = res.summary;
      if (res.protocol && res.protocol[0]) {
          urgencyLevel = res.protocol[0];
      }
      if (res.investigation && res.investigation.length > 0) {
        const itemObj = res.investigation[0].item[0] || {};
        const scoreMatch = itemObj.display?.match(/Calculated Score:\s*(\d+)/i);
        if (scoreMatch) clinicalScore = parseInt(scoreMatch[1], 10);
      }
    } else if (res.resourceType === 'CarePlan') {
      if (res.activity && res.activity.length > 0) {
        res.activity.forEach(act => {
          if (act.detail.kind === 'ServiceRequest') {
             instructions.push(act.detail.description);
          } else if (act.detail.kind === 'Appointment') {
             const parts = act.detail.description.match(/Referral to (.*?) at (.*?)\. Action: (.*)/);
             if (parts) {
               referral = { type: parts[1], location: parts[2], action: parts[3] };
             } else {
               referral = { type: "Referral", location: act.detail.description };
             }
          }
        });
      }
    }
  });

  const urgencyColors = {
    CRITICAL: '#ef4444',
    HIGH: '#f59e0b',
    MEDIUM: '#eab308',
    LOW: '#10b981',
    STABLE: '#10b981',
    UNKNOWN: '#64748b'
  };

  const currentColor = urgencyColors[urgencyLevel] || urgencyColors['UNKNOWN'];

  return (
    <motion.div 
      className="report-card glass"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8 }}
    >
      <div className="report-header" style={{ borderColor: currentColor }}>
        <div style={{ display: 'flex', gap: '8px' }}>
            <div className="urgency-badge" style={{ backgroundColor: currentColor + '22', color: currentColor }}>
            {urgencyLevel} URGENCY
            </div>
            {detectedLanguage && detectedLanguage.toLowerCase() !== 'english' && (
                <div className="urgency-badge" style={{ backgroundColor: '#1e293b', color: '#cbd5e1' }}>
                    LANG: {detectedLanguage.toUpperCase()}
                </div>
            )}
        </div>
        <div className="score-badge">Risk Score: {clinicalScore}</div>
        <h2>AetherMed Assessment Report</h2>
        <p className="timestamp">Generated: {new Date().toLocaleString()}</p>
      </div>

      <div className="report-section">
        <h3><Info size={18} /> Clinical Findings</h3>
        <div className="findings-list">
          <div className="finding-item">
            <strong>Observations:</strong> {observations.join(', ')}
          </div>
          <div className="finding-item">
            <strong>Analysis:</strong> {clinicalFindings}
          </div>
        </div>
      </div>

      <hr />

      <div className="report-section">
        <h3><CheckCircle size={18} /> Recommended Actions</h3>
        <ul className="advice-list">
          {instructions.map((r, i) => (
             <li key={i}><strong>Action:</strong> {r}</li>
          ))}
        </ul>
      </div>

      {referral && (
        <div className="referral-box" style={{ background: urgencyLevel === 'CRITICAL' ? 'rgba(239, 68, 68, 0.05)' : 'rgba(30, 41, 59, 0.3)' }}>
          <h3><MapPin size={18} /> Care Path</h3>
          <div className="referral-details">
            <div className="ref-type">{referral.type}</div>
            <div className="ref-facility">{referral.location}</div>
          </div>
        </div>
      )}

      <div className="disclaimer">
        ⚠️ This report was generated by the AetherMed Agentic system. This is a simulated assessment for hackathon purposes and does not constitute professional medical advice.
      </div>

      <div style={{ marginTop: '24px', borderTop: '1px solid var(--border-color)', paddingTop: '20px' }}>
        <button 
            className="reset-btn" 
            style={{ width: '100%', justifyContent: 'space-between', padding: '12px 16px', fontSize: '12px' }}
            onClick={() => setShowRaw(!showRaw)}
        >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Code size={14} /> View Interoperable FHIR R4 Bundle
            </div>
            {showRaw ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </button>

        <AnimatePresence>
            {showRaw && (
                <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    style={{ overflow: 'hidden' }}
                >
                    <pre style={{ 
                        background: '#0f172a', 
                        padding: '16px', 
                        borderRadius: '8px', 
                        marginTop: '12px', 
                        fontSize: '11px', 
                        color: '#94a3b8', 
                        overflowX: 'auto',
                        border: '1px solid #1e293b'
                    }}>
                        {JSON.stringify(data, null, 2)}
                    </pre>
                </motion.div>
            )}
        </AnimatePresence>
      </div>

      <style>{`
        .report-card { padding: clamp(20px, 5vw, 32px); margin-top: 24px; max-width: 800px; width: 100%; border-top: 4px solid var(--primary); }
        .report-header { margin-bottom: 24px; border-bottom: 1px solid var(--border-color); padding-bottom: 16px; }
        .urgency-badge { display: inline-block; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: 700; margin-bottom: 12px; letter-spacing: 0.5px; }
        h2 { margin: 0; font-size: clamp(1.25rem, 4vw, 1.5rem); color: #fff; line-height: 1.2; }
        .timestamp { font-size: 11px; color: #64748b; margin: 4px 0 0; }
        
        .report-section { margin-bottom: 24px; }
        h3 { display: flex; align-items: center; gap: 8px; font-size: 16px; color: var(--primary); margin-bottom: 16px; }
        
        .finding-item { margin-bottom: 12px; font-size: 14px; color: #cbd5e1; line-height: 1.6; }
        .finding-item strong { color: #f8fafc; display: block; margin-bottom: 2px; }
        
        .advice-list { list-style: none; padding: 0; margin: 0; }
        .advice-list li { position: relative; padding-left: 20px; font-size: 14px; margin-bottom: 12px; color: #cbd5e1; }
        .advice-list li::before { content: "→"; position: absolute; left: 0; color: var(--primary); }
        .advice-list li strong { color: #fff; }

        .referral-box { padding: clamp(16px, 4vw, 20px); border-radius: 12px; border: 1px dashed var(--border-color); margin-top: 32px; }
        .ref-type { font-weight: 700; font-size: clamp(1.125rem, 3.5vw, 1.25rem); color: #fff; }
        .ref-facility { font-size: 13px; color: var(--primary); margin: 4px 0 12px; }
        .ref-action { font-size: 13px; color: #cbd5e1; line-height: 1.5; }

        .disclaimer { margin-top: 32px; font-size: 11px; color: #64748b; font-style: italic; border-top: 1px solid var(--border-color); padding-top: 16px; text-align: center; line-height: 1.5; }
        hr { border: 0; border-top: 1px solid var(--border-color); margin: 24px 0; }

        @media (max-width: 480px) {
          .report-card { margin-top: 16px; border-radius: 12px; }
          .report-header { margin-bottom: 16px; }
          .referral-box { margin-top: 24px; }
        }
      `}</style>
    </motion.div>
  );
};

export default ReportCard;
